AcceptPortal/Controllers/PosEdit/PostEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcceptPortal.Filters;
using AcceptPortal.Models.Admin;
using System.IO;
using AcceptPortal.Resources;
using AcceptPortal.Utils;
using AcceptPortal.Models.PosEdit;
using AcceptPortal.ViewModels;
using AcceptPortal.Models.Evaluation;
using System.Text.RegularExpressions;
using System.Web.Routing;
using AcceptPortal.Models.Audit;
using AcceptPortal.Remote.PostEdit;
using AcceptPortal.Remote.Miscellaneous;

namespace AcceptPortal.Controllers.PosEdit
{
 
    [AcceptRequireHttps]  
    [Localization]  
    public class PostEditController : Controller
    {

        // GET: /PostEdit/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditFilter.AUDIT_DEFAULT_DESCRIPTION)]
        [Authorize]       
        public ActionResult Index()
        {
            List<Project> projects = PostEditRemoteMethods.GetProjectsByUser(User.Identity.Name);
          
            if (TempData.ContainsKey("ProjectUpdateMessage"))
            {
                ViewBag.ProjectUpdateMessage = TempData["ProjectUpdateMessage"];
                ViewBag.ProjectName = TempData["ProjectName"];
            }

            TempData.Remove("ProjectUpdateMessage");
            TempData.Remove("ProjectName");

            foreach (Project p in projects)
                p.UserRoleInProject = PostEditRemoteMethods.GetUserRolePostEditProject(User.Identity.Name, p.ID);

            return View(projects);
        }
       
        // GET: /PostEdit/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditFilter.AUDIT_DEFAULT_DESCRIPTION)]
        [Authorize]
        public ActionResult DemoProjects()
        {
            List<Project> projects = PostEditRemoteMethods.GetDemoProjects();                      
            foreach (Project p in projects)
                p.UserRoleInProject = PostEditRemoteMethods.GetUserRolePostEditProject(User.Identity.Name, p.ID);

            return View(projects);
        }

        [Authorize]
        public ActionResult CreateProject()
        {
            ProjectVM projectVm = new ProjectVM();         

            #region hardcoded language ID's
            //both source and target language ID's are hardcoded(bad conduct but no time (yet) available to change this...). 
            //if you plan to support more languages, advise you to create a method on the API side and get them.
            projectVm.SourceLanguageList.Add(new EvaluationLanguage(1, Global.English));
            projectVm.SourceLanguageList.Add(new EvaluationLanguage(2, Global.French));
            projectVm.SourceLanguageList.Add(new EvaluationLanguage(3, Global.German));
            projectVm.SourceLanguageList.Add(new EvaluationLanguage(6, Global.OtherLanguage));
            projectVm.TargetLanguageList.Add(new EvaluationLanguage(1, Global.English));
            projectVm.TargetLanguageList.Add(new EvaluationLanguage(2, Global.French));
            projectVm.TargetLanguageList.Add(new EvaluationLanguage(3, Global.German));
            projectVm.TargetLanguageList.Add(new EvaluationLanguage(6, Global.OtherLanguage));
            #endregion

            #region domain ID
            //the domain is somehow obsolete(the concept was about better grouping of pre-edit client instances and post-edit projects), it should be removed from the framework, however is hardcoded ID is a bad conduct too.            
            projectVm.DomainsList = MiscellaneousRemoteMethods.GetAllDomains();    
            #endregion

            //the defaults interpreted the client are: "1" for bilingual and "2" for monolingual.
            projectVm.ConfigurationList.Add(new ProjectUICongfiguration(1, Global.BiLingualLabel));
            projectVm.ConfigurationList.Add(new ProjectUICongfiguration(2, Global.MonoLingualLabel));

            //the defaults interpreted the client are: "1" for bilingual and "2" for monolingual.
            projectVm.UseTranslationOptions.Add(new ShowTranslationOptions(1, Global.LabelDisplayTranslationOptions));
            projectVm.UseTranslationOptions.Add(new ShowTranslationOptions(2, Global.DoNotDisplayTranslationOptions));

            //the defaults interpreted the client are: "1" for when user can switch to display source and "0" for when the source cannot be displayed.
            projectVm.CustomInterfaceConfigurationOptions.Add(new CustomInterfaceConfigurationOption(0, Global.NotAllowCustomUIValue));
            projectVm.CustomInterfaceConfigurationOptions.Add(new CustomInterfaceConfigurationOption(1, Global.AllowCustomUIValue));

            //the defaults interpreted the client are: "1" for paraphrasing enabled and "0" for paraphrasing disabled.
            projectVm.ParaphrasingModeOptions.Add(new ParaphrasingModeOption(0, Global.ParaphrasingDisabledLabel));
            projectVm.ParaphrasingModeOptions.Add(new ParaphrasingModeOption(1, Global.ParaphrasingEnabledLabel));

            //the defaults interpreted the client are: "1" for interactive check enabled and "0" for interactive check disabled.
            projectVm.InteractiveCheckOptions.Add(new InteractiveCheckOption(0, Global.InteractiveCheckDisabledLabel));
            projectVm.InteractiveCheckOptions.Add(new InteractiveCheckOption(1, Global.InteractiveCheckEnabledLabel));

            //getting the defaults for paraphrasing and interactive check: paraphrasing engine name, default rule-set per language, etc.
            projectVm.PostEditDefaults = PostEditRemoteMethods.GetParaprasingDefaults("all");
       
            //the paraphrasing metadata is the name for the engine used.
            projectVm.Project.ParaphrasingMetadata = projectVm.PostEditDefaults.SystemIdEnglish;

            #region interactive checks and paraphrasing endpoints defaults
            
            //default rule-sets.
            string[] rulesets = projectVm.PostEditDefaults.InteractiveChecksDefaultRuleSet.Split(',');
            ViewBag.EnglishRuleSet = rulesets[0];
            projectVm.Project.InteractiveCheckMetadata = rulesets[0];
            try
            {                
                ViewBag.FrenchRuleSet = rulesets[1];
                ViewBag.GermanRuleSet = rulesets[2];
            }
            catch {
                ViewBag.FrenchRuleSet = "";
                ViewBag.GermanRuleSet = "";
            }
            #endregion

            return View(projectVm);
        }

        // POST: /Project/Create
        [Authorize]
        [HttpPost]
        [AuditFilter(AuditAction = AuditFilter.CREATE, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.POSTEDIT_PROJECT_CREATED)]
        public ActionResult CreateProject(FormCollection collection)
        {
            try
            {                
                string domainId = collection["Project.ProjectDomain"];
                string projectName = collection["Project.ProjectName"];
                string[] projectOptions = collection["AllOptions"].Split(new string[] { "_$#$_" }, StringSplitOptions.RemoveEmptyEntries);                
                string sourceLanguageId = collection["Project.SourceLangId"];
                string targetLanguageId = collection["Project.TargetLangId"];
                string uiConfigurationId = collection["Project.InterfaceConfigurationId"];
                string projectAdmin = User.Identity.Name;
                string survey = collection["Project.ProjectSurvey"];
                string emailBody = collection["Project.EmailInvitationBodyText"];
                string showTransOptions = collection["Project.DisplayTranslationOptions"];
                string projectOrganization = collection["Project.Organization"];
                string question = collection["Project.ProjQuestion"];
                
                string[] projectQuestions;
                projectQuestions = question.Length > 0 ? projectQuestions = new string[] { question } : new string[] { };
                
                string customUiConfiguration = collection["Project.CustomInterfaceConfiguration"];
                bool isProjectExternal = bool.Parse(collection["Project.External"].Replace("true,false", "true").Replace("False,false", "false"));
                bool isSingleRevision = bool.Parse(collection["Project.SingleRevision"].Replace("true,false", "true").Replace("False,false", "false"));                                
                
                TimeSpan maxLockingSpan; maxLockingSpan = new TimeSpan();
                if (collection["Project.MaxThreshold"] != null)
                    maxLockingSpan = TimeSpan.Parse(collection["Project.MaxThreshold"]);

                string paraphrasingMode; paraphrasingMode = collection["Project.ParaphrasingMode"] != null ? paraphrasingMode = collection["Project.ParaphrasingMode"] : paraphrasingMode = "0";
                string interactiveCheck; interactiveCheck = collection["Project.InteractiveCheck"] != null ? interactiveCheck = collection["Project.InteractiveCheck"] : interactiveCheck = "0";
                string interactiveCheckMetadata; interactiveCheckMetadata = collection["Project.InteractiveCheckMetadata"] != null ? collection["Project.InteractiveCheckMetadata"] : string.Empty;                                
                string paraphrasingMetadata;paraphrasingMetadata = collection["Project.ParaphrasingMetadata"] != null ? collection["Project.ParaphrasingMetadata"] : string.Empty;

                Project p = PostEditRemoteMethods.CreateProject(PostEditRemoteMethods.getProjectJson(-1, projectName, domainId, "1", projectAdmin,
                projectQuestions, projectOptions, sourceLanguageId, targetLanguageId, uiConfigurationId,
                int.Parse(showTransOptions), emailBody, survey, projectOrganization,
                int.Parse(customUiConfiguration), isProjectExternal, isSingleRevision,

AcceptPortal/Views/PostEdit/AllProjectUsersPartial.cshtml
@model SelectList

<table id="tblUsersInProject" border="1">
    <thead>
    <tr>       
        <th>User Name</th>
        <th>Remove from Project ?</th>
    </tr>
    </thead>
    <tbody>
        @foreach (SelectListItem item in Model)
        { 
            
        <tr>          
            <td>@item.Text</td>
            <td><input type="checkbox" class="check-project-users" value="@Html.AttributeEncode(item.Text)" /></td>
        </tr>
            
        }

    </tbody>
</table>

AcceptPortal/Views/PostEdit/CreateProject.cshtml
@model AcceptPortal.ViewModels.ProjectVM

@{
    ViewBag.Title = AcceptPortal.Resources.Global.PostEditCreateProjectTitle;
}

@if ((User.IsInRole("Admin") || User.IsInRole("SIGAdmin"))) 
{

    <h2>@AcceptPortal.Resources.Global.PostEditCreateProjectTitle</h2>

    <div id="projectCreationPlaceholder" style="text-align:left;margin:0px;padding:0px;" class="">

@using (Html.BeginForm("CreateProject", "PostEdit", FormMethod.Post, new RouteValueDictionary(new { @id = "createProjectForm" })))
{                  
    
    @Html.ValidationSummary(true)
    
    <table border=0>
    <tr>
        
        <td width="200"><b>@Html.LabelFor(model => model.Project.ProjectName):</b></td>
        <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditProjectName" class="help-tooltip" /></td>
        <td width="200">
            @Html.EditorFor(model => model.Project.ProjectName)
            @Html.ValidationMessageFor(model => model.Project.ProjectName)
        </td>

    </tr>
    <tr>
    <td><b>@Html.LabelFor(model => model.Project.Organization):</b></td>
    <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditOrganization" class="help-tooltip" /></td>
    <td>
            @Html.EditorFor(model => model.Project.Organization)
            @Html.ValidationMessageFor(model => model.Project.Organization)
   </td>
    </tr>    
    <tr>
    <td><b>@Html.LabelFor(model => model.Project.ProjectDomain):</b></td>
    <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditProjectDomain"  class="help-tooltip" /></td>
        <td>
               @Html.DropDownListFor(model => model.Project.ProjectDomain, new SelectList(Model.DomainsList, "ID", "DomainName", Model.Project.ProjectDomain), new {@style = "height:35px;" })        

   </td>
    </tr>    
    <tr>
        <td><b>@Html.LabelFor(model => model.Project.SourceLangId):</b></td>
        <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditSourceLangId"  class="help-tooltip" /></td>
       <td>
               @Html.DropDownListFor(model => model.Project.SourceLangId, new SelectList(Model.SourceLanguageList, "ID", "Name", Model.Project.SourceLangId), new { @Id = "srcLang", @style = "height:35px;" })
       </td>
    </tr>

     <tr>
        <td><b>@Html.LabelFor(model => model.Project.TargetLangId):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditTargetLangId"  class="help-tooltip" /></td>
       <td>
          @Html.DropDownListFor(model => model.Project.TargetLangId, new SelectList(Model.TargetLanguageList, "ID", "Name", Model.Project.TargetLangId), new { @Id = "tgtLang", @style = "height:35px;" })             
       </td>
    </tr>


    <tr>
        <td><b>@Html.LabelFor(model => model.Project.InterfaceConfigurationId):</b></td>
        <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditMonoOrBilingual"  class="help-tooltip" /></td>
       <td>
          @Html.DropDownListFor(model => model.Project.InterfaceConfigurationId, new SelectList(Model.ConfigurationList, "ID", "Name", Model.Project.InterfaceConfigurationId), new { @style = "height:35px;" })      
       </td>
    </tr>
        <!--Paraphrasing Service.-->
            <tr>
            <td><b>@Html.LabelFor(model => model.Project.ParaphrasingMode):</b></td>
            <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditParaphrasingMode"  class="help-tooltip" /></td>
                <td>
            @Html.DropDownListFor(model => model.Project.ParaphrasingMode, new SelectList(Model.ParaphrasingModeOptions, "ID", "Label", Model.Project.ParaphrasingMode), new { @style = "height:35px;", @id = "ddlParaphrasing" })      
            </td>
            </tr>
            <tr>
            <td><b>@Html.LabelFor(model => model.Project.ParaphrasingMetadata):</b></td>
                <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditParaphrasingMetadata"  class="help-tooltip" /></td>
            <td>
            @Html.EditorFor(model => model.Project.ParaphrasingMetadata)
            @Html.ValidationMessageFor(model => model.Project.ParaphrasingMetadata)
            </td></tr>
       
        <!--Interactive Check.-->
          <tr>
            <td><b>@Html.LabelFor(model => model.Project.InteractiveCheck):</b></td>
              <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditInteractiveCheck"  class="help-tooltip" /></td>
            <td>
            @Html.DropDownListFor(model => model.Project.InteractiveCheck, new SelectList(Model.InteractiveCheckOptions, "ID", "Label", Model.Project.InteractiveCheck), new { @style = "height:35px;" })      
            </td>
            </tr>
            <tr>
            <td><b>@Html.LabelFor(model => model.Project.InteractiveCheckMetadata):</b></td>
            <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditInteractiveCheckMetadata"   class="help-tooltip" /></td>
                <td>
            @Html.EditorFor(model => model.Project.InteractiveCheckMetadata)
            @Html.ValidationMessageFor(model => model.Project.InteractiveCheckMetadata)
            </td>
            </tr>
        
            <!--Display Translation Options.-->
    <tr>
        <td><b>@Html.LabelFor(model => model.Project.DisplayTranslationOptions):</b></td>
        <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditDisplayTranslationOptions"  class="help-tooltip" /></td>
       <td width="400">
           @Html.DropDownListFor(model => model.Project.DisplayTranslationOptions, new SelectList(Model.UseTranslationOptions, "ID", "Label", Model.Project.DisplayTranslationOptions), new {@style = "height:35px;", @id = "ddlShowTranslationOptions"  })
       </td>
    </tr>


        <!--Allow To Display Source In The Client-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.CustomInterfaceConfiguration):</b></td>
       <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditUserCanCannotDisplaySource" class="help-tooltip" /></td>
         <td>
          @Html.DropDownListFor(model => model.Project.CustomInterfaceConfiguration, new SelectList(Model.CustomInterfaceConfigurationOptions, "ID", "Label", Model.Project.CustomInterfaceConfiguration), new { @style = "height:35px;" })      
       </td>
    </tr>
       

        <!--External Project.-->
    <tr>
        <td><b>@Html.LabelFor(model => model.Project.External):</b></td>
       <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")"  data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditExternalProject" class="help-tooltip" /></td>
        <td>
          @Html.CheckBoxFor(model => model.Project.External, new { @style = "height:35px;min-width:300px;width:100%;", @checked="" })      
       </td>
    </tr>

        <!--Single Revision Project.-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.SingleRevision):</b></td>
       <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditSingleRevisionProject"  class="help-tooltip" /></td>
         <td>
          @Html.CheckBoxFor(model => model.Project.SingleRevision, new { @style = "height:35px;min-width:300px;width:100%;", @checked = "", @id="chkSingleRevision" })                                              
       </td>     
    </tr>

     <tr>
        <td><b>@Html.LabelFor(model => model.Project.MaxThreshold):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditSingleRevisionMaxLockingPeriod"  class="help-tooltip" /></td>
       <td>@Html.TextBox("Project.MaxThreshold", Model.Project.MaxThreshold, new { @style = "height:35px;", @id = "inputMaxThreshold" })</td>
    </tr>
    
        <!--Display Pre-Defined Comments (Comment DDL Options in the Client).-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.ProjectOptions):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")"  data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditProjectCommentsDDLOptionsList" class="help-tooltip" /></td>
       <td>   
        <div class="space">
            @Html.TextBox("txtOptions") <label id="addOptionLabel" class="space" style="cursor:pointer;">[+]</label> <label id="removeOptionLabel" class="space" style="cursor:pointer;">[-]</label>
        </div>
        <div class="space">            
            <select multiple="multiple" id="optionsList" style="height:100px;"></select>        
        </div>
          @Html.HiddenFor(model => model.AllOptions, new { @id = "hddListOptions" })
       </td>
    </tr>

        <!--Question Prompted To User When Finishing Project Tasks.-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.ProjQuestion):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditProjectFinalQuestion"  class="help-tooltip" /></td>
       <td>
        @Html.EditorFor(model => model.Project.ProjQuestion)
            @Html.ValidationMessageFor(model => model.Project.ProjQuestion)
       </td>
    </tr>

         <!--Email Body Sent To User When Invited To Participate In The Project.-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.EmailInvitationBodyText):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditInvitationBodyText" class="help-tooltip" /></td>
       <td>
            @Html.EditorFor(model => model.Project.EmailInvitationBodyText)
            @Html.ValidationMessageFor(model => model.Project.EmailInvitationBodyText)
       </td>
    </tr>
    
        <!--Within The ACCEPT Portal This Link Is Shown When User Finishes All Tasks In The Project.-->
     <tr>
        <td><b>@Html.LabelFor(model => model.Project.ProjectSurvey):</b></td>
         <td class="help"><img src="@Url.Content("~/Content/images/circle_help.png")" data-original-title="@AcceptPortal.Resources.Global.HelpMessagePostEditProjectSurveyLink"   class="help-tooltip" /></td>
       <td>
              @Html.EditorFor(model => model.Project.ProjectSurvey)
            @Html.ValidationMessageFor(model => model.Project.ProjectSurvey)
       </td>
    </tr>

    <tr style="display:none">
        <td colspan="2">
              <input id="submitProjectCreation" style="display:none" type="submit" value="Create" />
        </td>
    </tr>
</table>                        
}
 </div>


<div style="margin:0px;float:left;padding:0px;">
    @Html.ActionLink(@AcceptPortal.Resources.Global.PostEditBackToListLabel, "Index") <input id="btnCreateProject" class="btn btn-primary" type="button" value="@AcceptPortal.Resources.Global.PostEditCreateProjectLabel"  />    
</div>

@section scripts{
<script type="text/javascript">
    var englishParaphrasingDefaultSystemId = @Html.Raw(Json.Encode(Model.PostEditDefaults.SystemIdEnglish));
    var frenchParaphrasingDefaultSystemId = @Html.Raw(Json.Encode(Model.PostEditDefaults.SystemIdFrench));
    var englishRuleSet = @Html.Raw(Json.Encode(ViewBag.EnglishRuleSet));
    var frenchRuleSet = @Html.Raw(Json.Encode(ViewBag.FrenchRuleSet));
    var germanRuleSet = @Html.Raw(Json.Encode(ViewBag.GermanRuleSet));
    var labelOthers =  @Html.Raw(Json.Encode(@AcceptPortal.Resources.Global.OtherLanguage));
    var message =  @Html.Raw(Json.Encode(@AcceptPortal.Resources.Global.PostEditSourceAndTargetLanguagesMustBeTheSame)); 
    var englishLanguageId = 1;
    var frenchLanguageId = 2;
    var germanLanguageId = 3;
</script>    
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/global/post-edit/create-project.js")" type="text/javascript"></script>
}
    
}else
{
    <div style="text-align:center;vertical-align:middle;margin-top:15%;" class="center"><img src="@Url.Content("~/Content/images/no-permission.jpg")" alt="" /></div>
}

AcceptPortal/Views/PostEdit/GetTaskStatusPartial.cshtml
@model  AcceptPortal.ViewModels.TaskStatusVM

@if (Model.UserTaskStatus.Any())
{  
     var count = 0;
       
    <table border="1">
        <tr>
        <td width="200"><b>@AcceptPortal.Resources.Global.TaskUserTableLabel</b></td>  
             @foreach (var task in Model.Tasks)
             {
                <td width="100"  title="@task">@AcceptPortal.Resources.Global.PostEditTaskLabel @{ count++; } @count</td>
             }                         
        </tr>
          
    @foreach (var user in Model.Users)
    {                                                                    
       <tr>
       <td width="200">@user</td>                       
       
       @foreach (var task in Model.Tasks)
       {

           int currentStatus = (from w in Model.UserTaskStatus
                                  where w.UserId == user && w.TextId == task
                                  select w.Status).First();

           string imgName = string.Empty;
           string statusLabelTitle = string.Empty;
                      
           switch (currentStatus)
           {
               case 0: { imgName = "taskNotStarted.png"; statusLabelTitle = @AcceptPortal.Resources.Global.TaskNotStartedLabel; } break;
               case 1: { imgName = "taskStarted.png"; statusLabelTitle = @AcceptPortal.Resources.Global.TaskStarted; } break;
               case 2: { imgName = "taskCompleted.png"; statusLabelTitle = @AcceptPortal.Resources.Global.TaskCompleted; } break;
               default: { imgName = string.Empty; } break;
           }
                                                
         <td width="200" title="@statusLabelTitle" style="text-align:center"> <img style="padding:2px;" alt="@statusLabelTitle" height="25" width="25" src="@Url.Content("~/Content/images/"+@imgName +"")" /></td>            
       }
       
       </tr>
    }

    </table>      
}
else
{ 
    <h2>@AcceptPortal.Resources.Global.ProjectRevisionsNotFoundLabel</h2>
}