AcceptPortal/Models/Download/FileDownloadResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcceptPortal.Models.Download
{
    public class FileDownloadResult : ContentResult
    {

        private string fileName;
        private byte[] fileData;
        public FileDownloadResult(string fileName, byte[] fileData)
        {
            this.fileName = fileName;
            this.fileData = fileData;
        }

        public override void ExecuteResult(ControllerContext context)
        {
            if (string.IsNullOrEmpty(this.fileName))
                throw new Exception("A file name is required.");
            if (this.fileData == null)
                throw new Exception("File data is required.");
            var contentDisposition = string.Format("attachment; filename={0}", this.fileName);
            context.HttpContext.Response.AddHeader("Content-Disposition", contentDisposition);
            ContentType = "application/force-download";
            context.HttpContext.Response.BinaryWrite(this.fileData);
        }
    
    }
}

AcceptPortal/Models/Download/FileExtensionMethods.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;

namespace AcceptPortal.Models.Download
{
    public static class FileExtensionMethods
    {
        public static byte[] GetFileData(this string fileName, string filePath)
        {

            var fullFilePath = string.Format("{0}/{1}", filePath, fileName);
            if (!File.Exists(fullFilePath))
            throw new FileNotFoundException("The file does not exist.",fullFilePath);
            return File.ReadAllBytes(fullFilePath);

        }            
    }
}

AcceptPortal/Controllers/Miscellaneous/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcceptPortal.Models.Download;
using System.IO;
using AcceptPortal.Filters;
using AcceptPortal.Models.Audit;

namespace AcceptPortal.Controllers
{
    [AcceptRequireHttps]   
    [Localization]
    [Authorize]    
    public class DownloadController : Controller
    {        
        // GET: /Download/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditFilter.AUDIT_DEFAULT_DESCRIPTION)]
        public ActionResult Index()
        {
            return View();
        }
        
        [AuditFilter(AuditAction = AuditFilter.CREATE, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.PREEDIT_PLUGIN_DOWNLOADED)]
        public FileDownloadResult DownloadFile(string file)
        {
            try
            {
                var fileData = file.GetFileData(Server.MapPath("~/Content/Files"));
                return new FileDownloadResult(file, fileData);
            }
            catch (FileNotFoundException)
            {
                throw new HttpException(404, string.Format("The file {0} was not found.", file));
            }
            finally
            { 
            
            }
        }
    }
}

AcceptPortal/Views/Download/Index.cshtml
@{
    ViewBag.Title = @AcceptPortal.Resources.Global.Download_Title;
}

<h1>@AcceptPortal.Resources.Global.Download_Title</h1>

<div class="div-place-holder" style="width:100%;height:auto;position:relative;">    
    <div style="left:10px;position:absolute;">
    <h4>@AcceptPortal.Resources.Global.Download_GettingStarted</h4>

    <p>
        @AcceptPortal.Resources.Global.Download_ParagraphOne
    </p>

    @Html.Partial("_LocalizationPartial", false)

    <a href="@Url.Action("DownloadFile", "Download", new { file = "accept-jquery-plugin-v3.0.zip" })">
        <img style="width:250px;" src="@Url.Content("~/Content/images/download_button.png")" alt="" />
    </a>

    </div>
</div>

AcceptPortal/Views/Download/_LocalizationPartial.cshtml
<p>
        @Html.Raw(string.Format(@AcceptPortal.Resources.Global.DownloadMainMessage, "href=\""+ @Url.Action("Index", "Documentation", new { @section = "pre" })+"\"",
        "href=\"http://jquery.com/\"",
        "href=\"http://jqueryui.com/\"",
        "href=\"" + @Url.Action("UserProfile", "PreEdit") + "\""));
</p>