AcceptPortal/Models/Evaluation/EvaluationDocument.cs
namespace AcceptPortal.Models.Evaluation
{
    public class EvaluationDocument
    {
        public EvaluationDocument() { }

        public EvaluationDocument(int id, string name)
        {
            ID = id;
            Name = name;
        }

        public  int ID { get; set; }
        public string Name { get; set; }

        public EvaluationProvider Provider { get; set; }
        public EvaluationLanguagePair LanguagePair { get; set; }

    }
}

AcceptPortal/Models/Evaluation/EvaluationLanguage.cs
namespace AcceptPortal.Models.Evaluation
{
    public class EvaluationLanguage
    {

        public EvaluationLanguage() { }

        public EvaluationLanguage(int id, string name)
        {
            ID = id;
            Name = name;
        }

        public  int ID { get; set; }
        public string Name { get; set; }
    }
}

AcceptPortal/Models/Evaluation/EvaluationLanguagePair.cs
namespace AcceptPortal.Models.Evaluation
{
    public class EvaluationLanguagePair
    {

        public EvaluationLanguagePair() { }

        public EvaluationLanguagePair(int id, string name)
        {
            ID = id;
            Name = name;
        }

        public  int ID { get; set; }
        public string Name { get; set; }
    }
}

AcceptPortal/Models/Evaluation/EvaluationProvider.cs
namespace AcceptPortal.Models.Evaluation
{
    public class EvaluationProvider
    {

        public EvaluationProvider() { }

        public EvaluationProvider(int id, string name)
        {
            ID = id;
            Name = name;
        }

        public  int ID { get; set; }
        public string Name { get; set; }
    }
}

AcceptPortal/Models/Evaluation/EvaluationType.cs
using System.ComponentModel;

namespace AcceptPortal.Models.Evaluation
{
    public enum EvaluationType
    {
        [Description("Embedded Evaluation")]
        Embedded = 1,

        [Description("External Evaluation")]
        External = 2
    }
}

AcceptPortal/Controllers/Admin/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcceptPortal.Models.Admin;
using AcceptPortal.Filters;
using AcceptPortal.Remote.PostEdit;

namespace AcceptPortal.Controllers.Admin
{
    [RequireHttps]
    [Localization]
    [Authorize]
    public class ProjectController : Controller
    {
        //
        // GET: /Project/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditFilter.AUDIT_DEFAULT_DESCRIPTION)]
        public ActionResult Index()
        {

            List<Project> projects = PostEditRemoteMethods.GetAllProjects();

            return View(projects);
        }

        //
        // GET: /Project/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Project/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Project/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                Project p = PostEditRemoteMethods.CreateProject(collection["ProjectName"], int.Parse(collection["DomainID"]), int.Parse(collection["Status"]));


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Project/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Project/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Project/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Project/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AcceptPortal/Controllers/Evaluation/EvaluationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using AcceptPortal.Models.Admin;
using System.IO;
using AcceptPortal.Models.Evaluation;
using AcceptPortal.Utils;
using AcceptPortal.Models.PosEdit;
using AcceptPortal.Filters;
using ICSharpCode.SharpZipLib.Zip;
using AcceptPortal.Models.Audit;
using AcceptPortal.Remote.Evaluation;
using AcceptPortal.Remote.Miscellaneous;
using AcceptPortal.ViewModels;
using System.Xml.Linq;
using AcceptPortal.Remote.PostEdit;
using System.Web.Routing;
using AcceptPortal.Resources;

namespace AcceptPortal.Controllers.Evaluation
{
    [AcceptRequireHttps]
    [Localization]
    [Authorize]
    public class EvaluationController : Controller
    {
        //
        // GET: /PostEdit/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditFilter.AUDIT_DEFAULT_DESCRIPTION)]
        public ActionResult Index()
        {
            string username = User.Identity.Name;
            List<EvaluationProject> projects = EvaluationRemoteMethods.GetEvaluationProjectsByUser(username);
            return View(projects);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<Project> projects = PostEditRemoteMethods.GetProjectsByUser(User.Identity.Name);
            List<SelectListItem> projectsList = new List<SelectListItem>();
            List<SelectListItem> projectsTypesList = new List<SelectListItem>();

            List<SelectListItem> evaluationMethods = new List<SelectListItem>();
            List<SelectListItem> duplicationApproachOptions = new List<SelectListItem>();


            projectsList.Add(new SelectListItem() { Text = Global.EvaluationProjectSelectLabel, Value = "-1" });

            foreach (Project p in projects)
            {
                if (p.ProjectOwner == User.Identity.Name)
                    projectsList.Add(new SelectListItem() { Text = p.ProjectName, Value = p.ID.ToString() });
            }

            projectsTypesList.Add(new SelectListItem() { Text = Global.EvaluationProjectExternalProjectLabel, Value = "2" });
            projectsTypesList.Add(new SelectListItem() { Text = Global.EvaluationProjectInternalLabel, Value = "1" });

            evaluationMethods.Add(new SelectListItem() { Text = Global.NotSet, Value = "0" });
            evaluationMethods.Add(new SelectListItem() { Text = Global.EvaluateOriginalLabel, Value = "1" });
            evaluationMethods.Add(new SelectListItem() { Text = Global.EvaluateOriginalAndAllRevisionsLabel, Value = "2" });
            evaluationMethods.Add(new SelectListItem() { Text = Global.EvaluateAllRevisionsOnlyLabel, Value = "3" });

            duplicationApproachOptions.Add(new SelectListItem() { Text = Global.NotSet, Value = "0" });
            duplicationApproachOptions.Add(new SelectListItem() { Text = Global.AvoidDuplicationTaskLevel, Value = "1" });
            duplicationApproachOptions.Add(new SelectListItem() { Text = Global.AvoidDuplicationProjectLevel, Value = "2" });

            @ViewBag.PostEditProjects = projectsList;
            @ViewBag.EvaluationProjectType = projectsTypesList;
            @ViewBag.EvaluationMethods = evaluationMethods;
            @ViewBag.DuplicationApproachOptions = duplicationApproachOptions;

            return View();
        }

        /// <summary>
        /// Create a New Evaluation Project
        /// </summary>
        /// <param name="collection">Collection of Form items</param>
        /// <returns></returns>
        [HttpPost]
        [AuditFilter(AuditAction = AuditFilter.CREATE, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.EVALUATION_PROJECT_CREATED)]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string evalProjectName = collection["Name"];
                string evalOrganization = collection["Organization"];
                string evalDescription = collection["Description"];
                string evalDomain = collection["Domain"];
                string username = User.Identity.Name;

                string evalProjectType = collection["EvaluationType"];
                string evalPostEditProjectId = collection["PostEditProjectId"] != null ? evalPostEditProjectId = collection["PostEditProjectId"] : evalPostEditProjectId = "-1";
                string evalMethod = collection["EvaluationMethod"] != null ? evalMethod = collection["EvaluationMethod"] : evalMethod = "0";
                string includeOwnerRev = collection["IncludeOwnerRevision"].Replace("true,false", "true").Replace("False,false", "false");
                string duplicationLogic = collection["DuplicationLogic"] != null ? duplicationLogic = collection["DuplicationLogic"] : duplicationLogic = "0";
                string emailBody = collection["CustomEmailBody"] != null ? emailBody = collection["CustomEmailBody"] : emailBody = string.Empty;

                EvaluationProject p = EvaluationRemoteMethods.CreateEvaluationProject(evalProjectName, evalDescription,
                    evalOrganization, evalDomain, username, evalProjectType, evalPostEditProjectId
                    , evalMethod, duplicationLogic, includeOwnerRev, emailBody);

                if (p != null && p.ID > 0)
                    return RedirectToAction("Questions", new { @Id = p.ID });
                else
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Demo()
        {
            ViewBag.EvaluationDemoQuestionUrl = CoreUtils.EvaluationDemoQuestionUrl;
            ViewBag.EvaluationDemoScoresUrl = CoreUtils.EvaluationDemoScoresUrl;
            ViewBag.EvaluationDemoApiKey = CoreUtils.EvaluationDemoApiKey;
            return View();
        }

        public ActionResult DemoMetrics()
        {
            var questions = EvaluationRemoteMethods.GetAllQuestions(3);
            var demoQuestion = new EvaluationQuestionItem();

            foreach (var item in questions)
            {
                foreach (var q in item.LanguageQuestions)
                {
                    if (q.ID == 5)
                    {
                        demoQuestion = q;
                    }
                }

            }

            return View(demoQuestion);
        }

        public ActionResult Project(int id)
        {
            EvaluationProject project = EvaluationRemoteMethods.GetEvaluationProject(id);
            return View(project);
        }

        [HttpPost]
        public ActionResult Project(int id, FormCollection collection)
        {
            return RedirectToAction("Edit", new { id = id });
        }

        public ActionResult AddData(int id)
        {
            ViewData["Documents"] = null;

            var documents = EvaluationRemoteMethods.GetEvaluationDocuments(id);
            ViewData["Documents"] = documents;

            EvaluationProject project = EvaluationRemoteMethods.GetEvaluationProject(id);
            return View(project);
        }

        public ActionResult AddDataFile(int id, int provider, int langpair)
        {
            ViewData["Documents"] = null;

            EvaluationProject project = EvaluationRemoteMethods.GetEvaluationProject(id);

            foreach (var p in project.Providers)
            {
                if (p.ID == provider)
                {
                    ViewData["providerid"] = p.ID;
                    ViewData["provider"] = p.Name;
                }
            }


            foreach (var l in project.LanguagePairs)
            {
                if (l.ID == langpair)
                {
                    ViewData["langpairid"] = l.ID;
                    ViewData["langpair"] = l.Name;
                }
            }

            return View(project);
        }

        [HttpPost]
        public ActionResult AddDataFile(int id, HttpPostedFileBase file, FormCollection collection)
        {
            bool bError = false;
            string errorMessage = string.Empty;

            int providerId = Convert.ToInt32(collection["providerid"]);
            int langpairId = Convert.ToInt32(collection["langpairid"]);

            if (file == null)
                return RedirectToAction("AddData", new { id = id });

            string originalFileName = Path.GetFileNameWithoutExtension(file.FileName);
            string filePath = originalFileName + "_" + Guid.NewGuid().ToString("N") + ".zip";
            string docsUploadPath = Server.MapPath("~/App_Data/uploads");

            if (docsUploadPath.StartsWith("~"))
            {
                docsUploadPath = Server.MapPath(docsUploadPath);
            }
            if (!Directory.Exists(docsUploadPath))
            {
                Directory.CreateDirectory(docsUploadPath);
            }

            filePath = Path.Combine(docsUploadPath, filePath);
            file.SaveAs(filePath);

            string tagerFolder = Path.Combine(docsUploadPath, Path.GetFileNameWithoutExtension(filePath));
            try
            {
                FastZip zip = new FastZip();
                zip.ExtractZip(filePath, tagerFolder, "\\.*$");
            }
            catch
            {
                bError = true;
                errorMessage = "Unable to extract ZIP archive";
            }

            string[] importFiles = new string[0];

            if (!bError)
            {
                if (Directory.Exists(tagerFolder))
                {
                    importFiles = Directory.GetFiles(tagerFolder);
                    if (importFiles.Length == 0)
                    {
                        bError = true;
                        errorMessage = "Upload archive was empty";
                    }
                }
                else
                {
                    bError = true;

AcceptPortal/Controllers/PreEdit/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcceptPortal.Filters;
using AcceptPortal.Models.Audit;
using AcceptPortal.Utils;

namespace AcceptPortal.Controllers.PreEdit
{

    [Authorize]
    [Localization]
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            return View("All");
        }
    
        // GET: /Demo/
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.PREEDIT_ALL_DEMO_PAGE_REQUESTED)]
        public ActionResult All()
        {
            return View();
        }

        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.PREEDIT_ENGLISH_DEMO_PAGE_REQUESTED)]
        public ActionResult English()
        {
            ViewBag.AcceptApiUrl = CoreUtils.AcceptPortalApiPath;           
            ViewBag.PreEditApiKey = CoreUtils.PreEditEnglishDemoPreEditApiKey;
            ViewBag.PreEditEnglishDemoDefaultRuleSet = CoreUtils.PreEditEnglishDemoPreEditDefaultRuleSet;
            return View();
        }

        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.PREEDIT_FRENCH_DEMO_PAGE_REQUESTED)]
        public ActionResult French()
        {
            ViewBag.AcceptApiUrl = CoreUtils.AcceptPortalApiPath;
            ViewBag.PreEditApiKey = CoreUtils.PreEditFrenchDemoPreEditApiKey;
            ViewBag.PreEditFrenchDemoDefaultRuleSet = CoreUtils.PreEditFrenchDemoPreEditDefaultRuleSet;
            ViewBag.PreEditFrenchDemoDefaultCheckingLevelsRuleSets = CoreUtils.PreEditFrenchDemoPreEditCheckingLevelsDefaultRuleSets.Split(',').ToArray();
            return View();
        }
                
        [AuditFilter(AuditAction = AuditFilter.READ, AuditType = AuditFilter.TYPEDEFAULT, AuditDescription = AuditDescriptor.PREEDIT_GERMAN_DEMO_PAGE_REQUESTED)]
        public ActionResult German()
        {
            ViewBag.AcceptApiUrl = CoreUtils.AcceptPortalApiPath;
            ViewBag.PreEditApiKey = CoreUtils.PreEditGermanDemoPreEditApiKey;
            ViewBag.PreEditGermanDemoDefaultRuleSet = CoreUtils.PreEditGermanDemoPreEditDefaultRuleSet;   
            return View();
        }

    }
}

AcceptPortal/Views/Evaluation/AddData.cshtml
@model AcceptPortal.Models.Evaluation.EvaluationProject

@{
    ViewBag.Title = "Add Data";
}

<h2>Add Project Data</h2>

<table border="0">
<tr>
<td><a href="@Url.Action("Edit", "Evaluation", new { Id = @Model.ID })">@AcceptPortal.Resources.Global.EvaluationEdit</a></td>
<td><a href="@Url.Action("Questions", "Evaluation", new { Id = @Model.ID })">@AcceptPortal.Resources.Global.EvaluationQuestions</a></td>
<td><a href="@Url.Action("AddData", "Evaluation", new { Id = @Model.ID })">@AcceptPortal.Resources.Global.EvaluationAddData</a></td>
<td><a href="@Url.Action("Metrics", "Evaluation", new { Id = @Model.ID })">@AcceptPortal.Resources.Global.EvaluationMetrics</a></td>
<td><a href="@Url.Action("ViewEvaluationData", "Evaluation", new { Id = @Model.ID, @token = @Model.AdminToken })">@AcceptPortal.Resources.Global.EvaluationViewData</a></td>
</tr>
</table>
<br />


@if (Model.Providers.Any())
{
    <table border="1">

    @foreach (var provider in Model.Providers)
    {
        <tr>
        <td>
        <h3>Provider: @provider.Name</h3>
        @if (Model.Providers.Any() && Model.LanguagePairs.Any())
        {
            <table border="1">
                @foreach (var langpair in Model.LanguagePairs)
                {
                    <tr>
                    <td>@langpair.Name</td>
                    <td>
                    

                    @if (ViewData["Documents"] != null)
                    {
                        foreach (var doc in (ViewData["Documents"] as List<AcceptPortal.Models.Evaluation.EvaluationDocument>).Where(p => p.Provider.ID == provider.ID && p.LanguagePair.ID == langpair.ID).ToList())
                        {
                            <span>doc.Name </span>
                        }
                    }
                    else
                    {
                        <span>No Files</span>
                    }

                    </td>
                    <td>
                        <a href="@Url.Action("AddDataFile", "Evaluation", new { Id = @Model.ID, provider = @provider.ID, langpair = @langpair.ID })">Add</a> |
                        <a href="#" runat="server" id="uxShowUploadDialog" onclick="return ShowUploadDialog(@provider.ID,@langpair.ID);">Add</a>
                     </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No data</p>
        }
        </td>
        </tr>
    }
    </table>
}
else
{ 
    <h3>No Providers Available</h3>
    <p>There are no providers added to this project.</p>
}

@using (Html.BeginForm("AddData", "Evaluation",
                    FormMethod.Post, new { enctype = "multipart/form-data", id = "uploadForm", name = "uploadForm" }))
{
<div id="uxUploadDialogForm" title="Upload">
 
    <p>Hello world</p>
    
    <input type="file" name="file" id="file" />

    <input type="submit" name="uxUpload" value="Upload" />

    <input type="hidden" name="dataParameters" id="orderNumber" value="0024" />
    
</div>
}

<script type="text/javascript">

    $(function () {

        dlg = $("#uxUploadDialogForm").dialog({
            autoOpen: false,
            modal: true
        });
    });

    function showDialog() {
        $("#example").dialog();
        return false;
    }
    function ShowUploadDialog(providerID, langID) {        
        $("#uxUploadDialogForm").dialog("open");
        return false;
    }

</script>

AcceptPortal/Views/Evaluation/Delete.cshtml
@model AcceptPortal.Models.Evaluation.EvaluationProject

@{
    ViewBag.Title = @AcceptPortal.Resources.Global.EvaluationDeleteProject;
}

<h2>@AcceptPortal.Resources.Global.EvaluationDeleteProject</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <table border="0">
    <tr>
    <td><a href="@Url.Action("Project", "Evaluation", new { Id =  @Model.ID })">Project</a></td>
    <td><a href="@Url.Action("Questions", "Evaluation", new { Id =  @Model.ID })">@AcceptPortal.Resources.Global.EvaluationQuestions</a></td>
    <td><a href="@Url.Action("Metrics", "Evaluation", new { Id =  @Model.ID })">@AcceptPortal.Resources.Global.EvaluationMetrics</a></td>    
    <td><a href="@Url.Action("ViewEvaluationData", "Evaluation", new { Id = @Model.ID, @token = @Model.AdminToken })">@AcceptPortal.Resources.Global.EvaluationViewData</a></td>
    </tr>
    </table>
    <br />

<h3>@AcceptPortal.Resources.Global.EvaluationDeleteMessageAll</h3>

    <table border="1">
    <tr>
        <td width="200"><b>@AcceptPortal.Resources.Global.EvaluationProjectID:</b></td>
        <td width="200">@Model.ID</td>
    </tr>
    <tr>
        <td width="200"><b>@AcceptPortal.Resources.Global.EvaluationName:</b></td>
        <td width="200">@Model.Name</td>
    </tr>
    <tr>
        <td><b>@AcceptPortal.Resources.Global.EvaluationOrganisation:</b></td>
        <td>@Model.Organization</td>
    </tr>
    <tr>
        <td><b>@AcceptPortal.Resources.Global.EvaluationDescription:</b></td>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <td><b>@AcceptPortal.Resources.Global.EvaluationAPIKey:</b></td>
        <td>@Model.ApiKey</td>
    </tr>
    <tr>
        <td><b>@AcceptPortal.Resources.Global.EvaluationAPIKeyDomain:</b></td>
        <td>@Model.Domain</td>
    </tr>
    <tr>
        <td colspan="2">
        @using (Html.BeginForm())
        {
              <input type="submit" value="@AcceptPortal.Resources.Global.EvaluationConfirm" /> <text>|</text> @Html.ActionLink(AcceptPortal.Resources.Global.EvaluationCancel, "Project", new { id = @Model.ID })
        }
        </td>
    </tr>
    
    </table>
 

AcceptPortal/Views/Evaluation/DeleteQuestionCategory.cshtml
@model AcceptPortal.Models.Evaluation.EvaluationQuestion

@{
    ViewBag.Title = @AcceptPortal.Resources.Global.EvaluationDeleteQuestionCategory;
}

<h2>@AcceptPortal.Resources.Global.EvaluationDeleteQuestionCategory</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <table border="0">
    <tr>
    <td><a href="@Url.Action("Project", "Evaluation", new { Id = ViewData["ProjectID"] })">Project</a></td>
    <td><a href="@Url.Action("Questions", "Evaluation", new { Id = ViewData["ProjectID"] })">@AcceptPortal.Resources.Global.EvaluationQuestions</a></td>
    <td><a href="@Url.Action("Metrics", "Evaluation", new { Id = ViewData["ProjectID"] })">@AcceptPortal.Resources.Global.EvaluationMetrics</a></td>    
    </tr>
    </table>
    <br />

<h3>@AcceptPortal.Resources.Global.EvaluationDeleteMessageAll</h3>

    <table border="1">
    <tr>
        <td width="200"><b>@AcceptPortal.Resources.Global.EvaluationID:</b></td>
        <td width="200">@Model.ID</td>
    </tr>
    <tr>
        <td width="200"><b>@AcceptPortal.Resources.Global.EvaluationCategoryName:</b></td>
        <td width="200">@Model.Name</td>
    </tr>
    <tr>
        <td colspan="2">
        @using (Html.BeginForm())
        {
            <input type="submit" value="@AcceptPortal.Resources.Global.EvaluationConfirm" /> <text>|</text> @Html.ActionLink(AcceptPortal.Resources.Global.EvaluationCancel, "Questions", new { id = ViewData["ProjectID"] })
        }
        </td>
    </tr>
    
    </table>

AcceptPortal/Views/Evaluation/Demo.cshtml
@{
    ViewBag.Title = @AcceptPortal.Resources.Global.EvaluationDemo;
}

<h2>@AcceptPortal.Resources.Global.EvaluationDemo</h2>

<div class="headerApps">    
    <ul class="horizontal-slide">
        <li><a class="underline-over" href="@Url.Action("Index", "Evaluation")">@AcceptPortal.Resources.Global.EvaluationManagement</a></li>
        <li><a class="underline-over" href="@Url.Action("Demo", "Evaluation")">@AcceptPortal.Resources.Global.EvaluationDemo</a></li>   
        <li><a class="underline-over" href="@Url.Action("DemoMetrics", "Evaluation")">@AcceptPortal.Resources.Global.EvaluationViewDemoMetrics</a></li>   
   </ul>
    </div>

<p>@AcceptPortal.Resources.Global.EvaluationDemoOverview</p>

<table border="0">
	<tr>
	<td>
	<div class="lia-message-view message-uid-147" id="messageview">
		<table border=1>
		<tr>
		<td width="200">
			<div name="voting" />
		</td>
		<td>
			<div class="content-source">
			This is a test sentence!
			</div>
		</td>
		<td>
			<div class="content-mt">
			    C'est une test phrase!
			</div>
		</td>
		</tr>
		</table>
	</div>
	</td>
	</tr>
	<tr>
	<td>
	<div class="lia-message-view message-uid-148" id="messageview">
		<table border=1>
		<tr>
		<td width="200">
			<div name="voting" />
		</td>
		<td>
			<a shape="rect" name="U148"> </a>
			<div class="content-source">
			This is another test sentence!
			</div>
		</td>
		<td>
			<div class="content-mt">
			C'est une autre test phrase!
			</div>
		</td>
		</tr>
		</table>
	</div>
	</td>
	</tr>
</table>

@section scripts{
<script type="text/javascript">
    var evaluationQuestionUrl = @Html.Raw(Json.Encode(ViewBag.EvaluationDemoQuestionUrl));
    var evaluationScoreUrl = @Html.Raw(Json.Encode(ViewBag.EvaluationDemoScoresUrl));
    var evaluationApiKey = @Html.Raw(Json.Encode(ViewBag.EvaluationDemoApiKey));
</script>
<script src="@Url.Content("~/Scripts/global/evaluation/demo-page.js")"></script>
}

AcceptPortal/Views/Evaluation/Tasks.cshtml
@model AcceptPortal.Models.Evaluation.EvaluationProject

@{
    ViewBag.Title = "Evaluation Project Tasks";
}

<h2>Project Tasks</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


<table border="1">
<tr>
<td><a href="@Url.Action("TaskBilingual", "Evaluation", new { Id = @Model.ID })">Bilingual</a></td>
</tr>
<tr>
<td><a href="@Url.Action("TaskMonoLingualSource", "Evaluation", new { Id = @Model.ID })">MonoLingual (Source)</a></td>
</tr>
<tr>
<td><a href="@Url.Action("TaskMonoLingualTarget", "Evaluation", new { Id = @Model.ID })">MonoLingual (Target)</a></td>
</tr>

</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AcceptPortal/Views/Evaluation/_UploadFile.cshtml
@ViewBag.Result